#!/usr/bin/env bash
# Regenerates app/assets/content/content_bundle.json from data/, via the
# content compiler (tools/content_compiler/compile.py), which itself runs
# nova_validate first and refuses to produce a bundle from invalid data.
#
# The bundle is a generated build artifact (gitignored, per Task 3 of
# docs/superpowers/plans/2026-09-22-nova-game-platform-vertical-slice.md)
# and is NOT committed to the repo -- it must be regenerated by this script
# after every fresh checkout, and after any change under data/, before
# building, running, or running the real-bundle integration test
# (app/test/core/game/game_runtime_real_bundle_test.dart).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# The validator's virtualenv: Scripts/ on Windows (Git Bash), bin/ elsewhere.
python=""
for candidate in tools/validate/.venv/Scripts/python.exe tools/validate/.venv/bin/python; do
  if [ -x "$candidate" ]; then python="$candidate"; break; fi
done
if [ -z "$python" ]; then
  echo "error: no Python virtualenv at tools/validate/.venv." >&2
  echo "Create it first (see README.md, 'Run the validator'):" >&2
  echo "  python -m venv tools/validate/.venv && tools/validate/.venv/bin/python -m pip install -r tools/validate/requirements.txt" >&2
  exit 1
fi
"$python" tools/content_compiler/compile.py
