#!/usr/bin/env bash
# Regenerates app/assets/content/content_bundle.json from data/, via the
# content compiler (tools/content_compiler/compile.py), which itself runs
# nova_validate first and refuses to produce a bundle from invalid data.
#
# The bundle is a generated build artifact (gitignored, per Task 3 of
# docs/superpowers/plans/2026-09-22-nova-game-platform-vertical-slice.md)
# and is NOT committed to the repo -- it must be regenerated by this script
# after every fresh checkout, and after any change under data/, before
# building, running, or running the real-bundle integration test
# (app/test/core/game/game_runtime_real_bundle_test.dart).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
tools/validate/.venv/Scripts/python.exe tools/content_compiler/compile.py
